[project]
name = "sfm"
version = "0.1.0"
authors = [
  { name = "Hanna Lee", email = "hanna.lee@alleninstitute.org" },
]
readme = "README.md"
requires-python = "~=3.8"
dependencies = [
  "pycolmap==3.11"
]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]