[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sfm"
version = "0.3.0"
authors = [
  { name = "Hanna Lee", email = "hanna.lee@alleninstitute.org" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pycolmap==3.11",
  "plotly",
  "opencv-python",
  "h5py",
  "Pillow",
  "tqdm",
  "lightglue @ git+https://github.com/cvg/LightGlue.git",
  
  # Python 3.10+
  'torch>=2.5.1; python_version >= "3.10"',
  'torchvision>=0.20.1; python_version >= "3.10"',
  'numpy>=1.24.4; python_version >= "3.10"',

  # Python < 3.10 (e.g., 3.8/3.9)
  'torch==2.4.1; python_version < "3.10"',
  'torchvision==0.19.1; python_version < "3.10"',
  'numpy<2.0; python_version < "3.10"',
]


[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.setuptools.package-data]
"sfm.dataset.reticle_model" = ["*"]

[tool.setuptools]
include-package-data = true
