[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sfm"
version = "0.3.0"
authors = [
  { name = "Hanna Lee", email = "hanna.lee@alleninstitute.org" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pycolmap==3.11",
  "plotly",
  "opencv-python",
  "h5py",
  "Pillow",
  "tqdm",
  "lightglue @ git+https://github.com/cvg/LightGlue.git",
  "torch>=2.5.1",
  "torchvision>=0.20.1",
  "numpy>=1.24.4",
]


[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.setuptools.package-data]
"sfm.dataset.reticle_model" = ["*"]

[tool.setuptools]
include-package-data = true
